language: csharp
solution: LinqToAStar.sln
dist: trusty
mono: none
dotnet: 2.0.0

install:
- dotnet restore src/LinqToAStar.sln

script:
- dotnet build src/LinqToAStar.sln
- dotnet test src/LinqToAStar.Test/LinqToAStar.Test.csproj -c Release